name: Generate Javadocs

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build Project
        run: mvn clean compile

      - name: Generate Javadocs
        run: timeout 300 javadoc -d docs -sourcepath "client/src/main/java:server/src/main/java:shared/src/main/java" -subpackages chess:clienttoserver:dataaccess:model:server.websocket:server:service:ui:websocket.commands:websocket.messages -classpath "$(mvn -q dependency:build-classpath -Dmdep.outputFile=/dev/stdout)"

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          publish_dir: docs
